### ISSUE TITLE
Chapter 7 cannot create new fundraisers on Hands-On Smart Contract Development with Solidity and Ethereum

### ISSUE THREAD

**Issue by bunmin** [RedSquirrelTech/hoscdev#30]
I have done reading and following the chapter 7 of the book "Hands-On Smart Contract Development with Solidity and Ethereum".
And there said that i could create the new fundraiser from browser, but when i am try, it display error like this : 

![image](https://user-images.githubusercontent.com/28707462/97951729-c412ce00-1dcd-11eb-81b0-4355baaa5111.png)

please tell me how to solve this problem.

**Comment by JeanGalt1957** [comment]
@bunmin I have the exact same error, bunmin. Could you kindly let me know how you fixed it? Would be much appreciated!

**Comment by bunmin** [comment]
@JeanGalt1957, sorry about that jean, i am forget how fixed it but my code worked, you can see in (https://github.com/bunmin/learnBC-handsonsc-chap7) and compare with your code, i hope your can solved this problem too.

**Comment by redsquirrel** [comment]
Sorry for the lack of response, @bunmin and @JeanGalt1957. We will look to update this.

**Comment by JeanGalt1957** [comment]
Thanks @redsquirrel. @bunmin mentioned he got his code to work so I’ll try his repo this week or weekend. I did a fresh install of my Ubuntu subsystem and installed an older version of Node. Fingers crossed between those three solutions I can get the UI working. I’ll post an update with the result

**Comment by JeanGalt1957** [comment]
@redsquirrel I'm using bunmins repo above -- all compiles correctly and tests as passing. When I try NPM run start I get the following error:

Failed to compile.

./src/NewFundraiser.js
Module not found: Can't resolve 'web3' in '/home/user/ch7reop/client/src'

**Comment by bunmin** [comment]
@JeanGalt1957 you are need run "npm i" in client directory.

**Comment by JeanGalt1957** [comment]
thanks @bunmin, I've done that every which way! I run into a lot of errors with the NPM package manager (npm fails on gyp and sha3). I was able to work around it but loading an earlier version of node and got all dependencies installed (with some warnings) -- that's when i ran into your error screen in the localhost site...

I'll try to run it again tomorrow from a fresh clone of your repo.

@redsquirrel Dave any idea how to overcome the dependency install issues in /client? Seems like a common problem for people using React from googling around (a lot!)

**Comment by redsquirrel** [comment]
I appreciate the help on this @bunmin. @JeanGalt1957 I need to defer to @randallkanna and @ksolo to help troubleshoot this issue when/if they have availability. This part of the book isn't my area of expertise. 😕

**Comment by ksolo** [comment]
@JeanGalt1957 At the time of writing the app required an older version of Node due to some of the dependencies in Truffle. The book specifies using Node 10, which has an EOL coming up in April. I'll check to see if those items have been updated.

**Comment by JeanGalt1957** [comment]
@ksolo thanks for the response. I've tried node 10 and even earlier versions of node -- the package manager always manages to fail (the one time it finished it had tons of warnings, and that's what led to the error page in the localhost that bunmin posted). Usually I can't even get run start to compile

I'd say maybe its something with my machine but I successfully ran and deployed the truffle petshop tutorial which also has a nice UI...

I would *really* appreciate some help here. At present, I have purchased a book that is simply not useable. What bunmin and I don't mention is that the code in you repo does not even compile. Oppenzeppelin has a new file structure for ownable.sol, the fallback function in solidity requires a different syntax, and those are just a couple examples. Yes they can be worked around but for a beginner trying to learn this tech it's unbelievably frustrating that I can't even run the book's github code. I allow that the technology is young and evolving, but if things are this out of date and there is no intention to maintain or update the repo then it is unethical to sell the book in its current state. I'm willing to look past it for now given @redsquirrel Dave and yourself have at least responded, which I appreciate.

**Comment by ksolo** [comment]
@JeanGalt1957 Can you provide more information on your issue? It would be helpful to see the command and the following output to get a better idea of what's going on. It could be things like missing system dependencies or other assumed implicit requirements.

I plan on spending some time updating the repo next week to resolve these issues and send errata to O'Reilly for an update, which will hopefully help you and other future readers.

**Comment by JeanGalt1957** [comment]
@ksolo Kevin thanks, I am happy to provide details -- please let me know if I can provide any thing else in addition

I just recreated the error from a clean hoscdev chapter-7 repo. Here is the fulder structure:
![Root Fundraiser tree](https://user-images.githubusercontent.com/76701492/104072979-96397380-51da-11eb-83fd-c1895435ff4a.PNG)
note, you must do the following to get successful compilation (and note my locat port if 7545): 
Install openzeppelin
    npm install @openzeppelin/contracts
Change imports in fundraiser.sol to 
    import "@openzeppelin/contracts/access/Ownable.sol";
    import "@openzeppelin/contracts/math/SafeMath.sol";
change fallback function in fundraiser.sol line 90 to 
    Fallback () …
Remove underscore in line 43 in fundraiser.sol
Update default compiler in config, add below network block:
    compilers: {
         solc: {
              version: “0.6.0”  // ex:  "0.4.20". (Default: Truffle's installed 
              solc)
                 },
Update solidity version in line one of contracts/migrations.sol
    pragma solidity >0.4.23 <0.7.0;
Change port from 8545 to 7545 in ~/truffle-config.js and ~/client/src/utils/getWeb.js

Here are my versions of node, npm and truffle
![node, npm and truffle versions](https://user-images.githubusercontent.com/76701492/104073213-152eac00-51db-11eb-8d00-87dc031cebef.PNG)

I then run npm i in ~/client and install a lot of packages, ultimately ending with some errors
![npm i output](https://user-images.githubusercontent.com/76701492/104073294-4d35ef00-51db-11eb-9bf5-f764b57f874f.PNG)

I then npm run start and get a compilation failure
![run start failure](https://user-images.githubusercontent.com/76701492/104073340-6a6abd80-51db-11eb-8fe3-f25f2d6aed81.PNG)

I also tried npm run build (which gives a more detailed error log)
![run build failure](https://user-images.githubusercontent.com/76701492/104073377-81111480-51db-11eb-88d8-d020c325f50f.PNG)

**Comment by ksolo** [comment]
@JeanGalt1957 
One of the first errors that sticks out to me is the missing C compiler. Can you install gcc?
```
$ sudo apt-get update
$ sudo apt-get install gcc
```

The second error from the same package is a permissions error. You may need to run the npm install command with sudo as well

```
$ sudo npm install
```

I normally use a version manage like [asdfvm](https://asdf-vm.com/#/) which prevents the need for sudo, but that's not a requirement.

**Comment by JeanGalt1957** [comment]
@ksolo, appreciate the tips. Ran fresh and used both commands to get C compiler. Still get the same run start failure -- see below for the sudo npm install in /client, error looks a bit different - I've hit this gyp error a few times, I know once I managed to get thru it but can't remember how...have you any suggestions?
![sudo NPM i error](https://user-images.githubusercontent.com/76701492/104082985-a9fbce80-5208-11eb-802f-0604a3f96d30.PNG)

**Comment by ksolo** [comment]
@JeanGalt1957 this is a new failure though it is the same library causing it.

You need to install make, but I'm guessing you may want to go ahead and install the build essential lib which includes it and other common system dev tools.

Try

sudo apt-get install build-essential

**Comment by JeanGalt1957** [comment]
@ksolo, thanks Kevin - the build-essential seems to have installed correctly. I am still getting the same run start error "Can't resolve './contracts/SimpleStorage.json'"

Below is the new npm i output. It was long but I did not see any errors...a couple warns on optional dependiencies. And no debug log. Any idea on what I can try next? 
![sudo npm i success](https://user-images.githubusercontent.com/76701492/104103620-190d0d80-5271-11eb-9e93-3931b87fa071.PNG)

**Comment by JeanGalt1957** [comment]
@ksolo I actually just noticed noticed in line 2 of /client/src/App.js there is "import SimpleStorageContract from "./contracts/SimpleStorage.json";

The SimpleStorage.json file doesn't exist in the chapter-7 repo...is that right?

**Comment by ksolo** [comment]
@JeanGalt1957 The `SimpleStorage` contract is a sample contract that is, or at least was at the time of writing, created when you initialize the truffle react box. Any reference to `SimpleStorage` can/should be removed.

**Comment by JeanGalt1957** [comment]
@ksolo so is the chapter-7 repository wrong? Check the App.js in the repository...must the be wrong UI. I'll give it a try and also from Bunin's code which seems aligned with the book's...

https://github.com/RedSquirrelTech/hoscdev/blob/master/chapter-7/fundraiser/client/src/App.js

**Comment by JeanGalt1957** [comment]
@ksolo Kevin, I'll reset tomorrow. It appears the .sol needed are in /chapter-7  and the UI packages are in /client chapter-9...will update you with output of any errors

**Comment by JeanGalt1957** [comment]
@ksolo good progress! Hopefully this gets us closer to a solution -- 

I used chapter-7 and replaced the /client folder with the contents of chapter-9. The `npm install` worked fine and deployed to development with no problem -- and `run start` compiled and `localhost` launched! Now however I have replicated the *exact* same error that bunmin started on this thread. Two things:

1)  when I launch local host and metamsk pops up, i select the account but then get an error message saying 'failed to load web3, accounts, or contract:
![localhost error_2021 01 10_0026](https://user-images.githubusercontent.com/76701492/104115353-8ace7100-52dc-11eb-8223-502c63ccb25f.PNG)

2) the UI exists but is a skeleton, and when I click 'new' and submit a dummy fundraiser, I generate the same error message Bunmin did:
![new contract error_2021 01 10_0027](https://user-images.githubusercontent.com/76701492/104115364-cb2def00-52dc-11eb-96aa-e2489aa9d3bf.PNG)

I am including below some of the `run start `compilation warnings in case these are relevant
![run start compile_2021 01 10_0034](https://user-images.githubusercontent.com/76701492/104115402-1c3de300-52dd-11eb-9c77-0993c4b437ef.PNG)

**Comment by JeanGalt1957** [comment]
@ksolo, Kevin looked at this again today and wanted to share one more error output associated with the 'new contract' functionality -- when I click submit it also feeds this error into my terminal window:
![run start console message_2021 01 10_1633](https://user-images.githubusercontent.com/76701492/104136051-c3fcf480-5361-11eb-8791-fcb30e5c620e.PNG)

**Comment by ksolo** [comment]
@JeanGalt1957 Can you link me to your code so I can see your full application? Based on the error, I think at least one contract was not loaded properly. This could be a typo, a missing await (the contract was never assigned), a change in the web3 api, or something else entirely.

**Comment by JeanGalt1957** [comment]
@ksolo thanks so much, Kevin. I posted my repo here without node_modules folders. Note this is the result of taking ch7 from this repo and replacing /client with the client folder from chapter-10+11 folder. The only other changes are the ones I noted a few posts above to get successful compilation (updating openzep import, updated solc compiler, local port of 7545 and some other nits). Please let me know if any qs or issues, otherwise you should be able to replicate!

https://github.com/JeanGalt1957/hoscdev_ch7/tree/main/fundraiser

**Comment by ksolo** [comment]
@JeanGalt1957 
I spent a fair amount of time on this today and found several things:
1 - This may be something to do with React Router but when you click on the New link, it does not seem to run the useEffect hook, but if you refresh the page on that route, it does. The useEffect hook is what sets the web3 instance, without that running when you attempt to access `currentProvider` or any of the methods associated with the contracts they fail.
2 - Ownable seems to have changed and the transaction creating the fundraiser is now failing. I'm looking into this now.

@randallkanna Do you have any insight into why the useEffect hook (specifically the `init` function defined there) is not firing when navigating from the home page?

**Comment by JeanGalt1957** [comment]
Thanks Kevin, will keep an eye out for further info. Sounds like you can replicate what I was seeing. Re: item #1 you mentioned ‘refreshing the page on that route’, what do you mean by this? Is it a workaround I can use in the interim? Apologies, I’m quite new to react.

As usual appreciate the help here...we’ll figure something out yet!

Matt Gilbertson
(732) 233-3831
________________________________

**Comment by ksolo** [comment]
@JeanGalt1957 The last message had your phone number in it, likely from an email signature. I deleted it but not sure if anything scraped it or not.

I will share a few of the changes I made with you later today.

**Comment by JeanGalt1957** [comment]
Oh jeez, thanks for catching that!

**Comment by JeanGalt1957** [comment]
@ksolo thanks again Kevin for catching the earlier comment. Any chance you could share the changes you made? Found a way to get it working? Eager to keep moving thru the book!!

**Comment by ksolo** [comment]
@JeanGalt1957 
I made a few changes to the `truffle-config.js`
1. added the `contracts_build_directory`[(more on config)](https://www.trufflesuite.com/docs/truffle/reference/configuration#contracts_build_directory) option pointing it to the `client/src/contracts` directory in your project
2. updated the network port to 8545 (new default for ganache)

I also updated the port in the `client/src/utils/getWeb3.js` file

Navigating to the /new/ page will work on links, but it doesn't execute the `init` function. At this point I refreshed and it loaded things properly. I haven't looked into this further since last week yet.

The contracts can send the trasaction properly after I've done these things, but the transaction is not successful. This is something I still need to look into as well.

**Comment by JeanGalt1957** [comment]
Thanks a lot for looking at this @ksolo, I’ll give it a shot. I have been swamped the last few days but will check out the code this week!

**Comment by JeanGalt1957** [comment]
@ksolo sorry if I missed it but have you published the code with the changes you made? If not that's fine just wanted to give it a try

**Comment by JeanGalt1957** [comment]
@ksolo @randallkanna made some serendipitous progress - without changing any code since my post 12 days ago (https://github.com/RedSquirrelTech/hoscdev/issues/30#issuecomment-758102163) I am able to successfully transact between accounts in my local block chain in the 'New' page when clicking submit - all of the fields can be dummy data except 'address' - which MUST be set to the active account in MetaMask (this was my error, I must have had a typo or was trying a random account). Side note, the custodian account appears to be able to be set to whatever you want so long as it is a valid address in ganache). By default, the successful transaction goes to an account not in my ganache instance (see circled in red). I can also edit the recipient and transact between my ganache accounts (see highlighted in yellow):

![toAccountIndex2andRand](https://user-images.githubusercontent.com/76701492/105612922-3e2f6f00-5d8d-11eb-9fec-0a5a3f89dea1.PNG)

for reference, see my ganache instance below, the red circle account is not any of them, and the yellow highlight is account index 2:

![GanacheInstance](https://user-images.githubusercontent.com/76701492/105613065-1b518a80-5d8e-11eb-8cfc-cdf97872c681.PNG)

However, even **_after successfully executing a transaction in the 'New' page, when I navigate back to 'Home' I still get a blank page_** and the 'can't load contracts...' error

![cant load](https://user-images.githubusercontent.com/76701492/105612958-76cf4880-5d8d-11eb-901b-1d938f374834.PNG)

Anyway, hopefully this is somewhat helpful in moving towards solving the home page UI issue
